checks:
  python:
    code_rating: true
    duplicate_code: true
  javascript: true

build:
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        before:
#          - 'sudo apt-get install chromium-browser'
          - 'pip3 install coverage'
#          - 'pip3 install pyvirtualdisplay'
        override:
          -
            command: echo OK
#            command: 'coverage run --omit=manga_py/providers/*.py --source=manga_py pytest.py'
            coverage:
              file: '.coverage'
              format: 'py-cc'
#          - py-scrutinizer-run
      environment:
        python: 3.5.3
        node: 6.0.0
filter:
  excluded_paths:
    - tests/*.py
    - pytest.py